/**
 * Reserved handles to protect infrastructure and prevent obvious impersonation.
 * Keep this list minimal. Do not reserve excessive legitimate names.
 */

export const RESERVED_HANDLES: readonly string[] = [
  // Core infrastructure
  "admin",
  "administrator",
  "api",
  "app",
  "about",
  "claim",
  "manage",
  "protocol",
  "support",
  "help",
  "docs",
  "status",
  "health",
  "root",
  "www",
  "mail",
  "email",
  "ftp",
  "cdn",
  "static",
  "assets",
  "public",
  "private",
  "system",
  "null",
  "undefined",
  "test",
  "testing",
  "demo",
  "example",
  "sample",

  // Project / brand
  "tipmebitcoin",
  "tipme",
  "tip",
  "bitcoin",
  "bitcoincash",
  "bch",
  "cashtoken",
  "cashtokens",
  "cash",
  "token",
  "tokens",

  // Impersonation / official-looking
  "official",
  "officialbch",
  "bchofficial",
  "team",
  "staff",
  "mod",
  "moderator",
  "security",
  "verify",
  "verification",
  "support-team",
  "helpdesk",
  "customer",
  "service",

  // Common reserved words
  "login",
  "logout",
  "signup",
  "register",
  "account",
  "profile",
  "settings",
  "dashboard",
  "home",
  "index",
  "search",
  "explore",
  "feed",
  "wallet",
  "wallets",
  "address",
  "addresses",
  "qr",
  "pay",
  "payment",
  "payments",
  "send",
  "receive",
  "donate",
  "donation",
  "donations",
  "tipjar",
  "tip-jar",

  // Protocol related
  "cashaccount",
  "cashaccounts",
  "identity",
  "id",
  "resolver",
  "registry",
] as const;

export function isReservedHandle(normalized: string): boolean {
  return RESERVED_HANDLES.includes(normalized.toLowerCase());
}
